---
# tasks file for easy_rsa (Ubuntu specific)

- name: Check easy-rsa packages
  become: no
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ easy_rsa_packages }}"
  tags:
    - easy_rsa
